package main

import (
	"errors"
	"fmt"
	"os"
	"path"
	"slices"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

const (
	EnvCradleHome        = "CRADLE_HOME"
	CradleConfigFileName = "cradle.toml"

	CradleConfigFileHeader = `# Code generated by cradle. DO NOT EDIT.`
)

// CradleConfig represents the cradle.toml file
type CradleConfig struct {
	Projects []CradleProject
}

type Config struct {
	CradleHomeDirPath    string
	CradleConfigFilePath string
	CradleConfig         CradleConfig
}

var config *Config

func InitConfig() error {
	config = &Config{}

	cradleHomePath, err := getCradleHomeDir()
	if err != nil {
		return err
	}

	// Make sure home directory exists.
	err = ensureCradleHomeDir(cradleHomePath)
	if err != nil {
		return err
	}

	// Make sure cradle config file exists
	cradleConfigFilePath, err := ensureCradleConfigFile(cradleHomePath)
	if err != nil {
		return err
	}

	// Parse the config file
	cradleConfig, err := parseCradleConfigFile(cradleConfigFilePath)
	if err != nil {
		return err
	}

	config.CradleHomeDirPath = cradleHomePath
	config.CradleConfigFilePath = cradleConfigFilePath
	config.CradleConfig = cradleConfig

	return nil
}

func getCradleHomeDir() (string, error) {
	cradleHomePath := strings.TrimSpace(os.Getenv(EnvCradleHome))
	if cradleHomePath == "" {
		userHomeDir, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}

		cradleHomePath = path.Join(userHomeDir, "cradle")
	}

	return cradleHomePath, nil
}

func ensureCradleHomeDir(dirPath string) error {
	dirStat, err := os.Stat(dirPath)
	if err != nil {
		// Directory doesn't exist, try to create it (including parents).
		if errors.Is(err, os.ErrNotExist) {
			err := os.MkdirAll(dirPath, os.ModePerm)
			if err != nil {
				return err
			}

			return nil
		}

		return err
	}

	// Directory already exists, we are good.
	if dirStat.IsDir() {
		return nil
	}

	return fmt.Errorf("%s is a file, either delete the file or change cradle home path by setting `CRADLE_HOME` env to something else", dirPath)
}

func ensureCradleConfigFile(dirPath string) (string, error) {
	configFilePath := path.Join(dirPath, CradleConfigFileName)

	configFileStat, err := os.Stat(configFilePath)
	if err != nil {
		// File doesn't exist, create it.
		if errors.Is(err, os.ErrNotExist) {
			configFile, err := os.Create(configFilePath)
			if err != nil {
				return "", err
			}

			_, err = configFile.WriteString(CradleConfigFileHeader)
			if err != nil {
				return "", err
			}

			return configFilePath, nil
		}

		return "", err
	}

	if configFileStat.IsDir() {
		return "", fmt.Errorf("")
	}

	// File already exists
	return configFilePath, nil
}

func parseCradleConfigFile(configFilePath string) (CradleConfig, error) {
	var cradleConfig CradleConfig

	configFile, err := os.ReadFile(configFilePath)
	if err != nil {
		return cradleConfig, err
	}

	err = toml.Unmarshal(configFile, &cradleConfig)
	if err != nil {
		return cradleConfig, err
	}

	slices.SortFunc(config.CradleConfig.Projects, func(a, b CradleProject) int {
		return strings.Compare(a.Path, b.Path)
	})

	// Generate unique names for each project based on their paths
	// The unique name is generated by taking the last parts of the path
	// until a unique name is found.
	nameLookup := make(map[string]struct{})
	for i, project := range cradleConfig.Projects {
		parts := strings.Split(project.Path, string(os.PathSeparator))
		for j := len(parts) - 1; j >= 0; j-- {
			candidateName := strings.Join(parts[j:], "/")
			if candidateName == "" {
				continue
			}

			if _, exists := nameLookup[candidateName]; !exists {
				cradleConfig.Projects[i].UniqueNameFromPath = candidateName
				nameLookup[candidateName] = struct{}{}
				break
			}
		}
	}

	return cradleConfig, nil
}

func UpdateCradleConfigFile() error {
	slices.SortFunc(config.CradleConfig.Projects, func(a, b CradleProject) int {
		return strings.Compare(a.Path, b.Path)
	})

	fileBytes, err := toml.Marshal(config.CradleConfig)
	if err != nil {
		return err
	}

	fileBytes = append([]byte(CradleConfigFileHeader+"\n\n"), fileBytes...)

	return os.WriteFile(config.CradleConfigFilePath, fileBytes, 0666)
}
