# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  generate-vhs:
    dir: ./docs/vhs
    cmd: 'parallel --progress --bar --tag vhs {} ::: list.tape main.tape'
    silent: true
