package config

import (
	"errors"
	"fmt"
	"os"
	"path"
	"slices"
	"strings"

	"github.com/gurleensethi/cradle/internal/types"
	"gopkg.in/yaml.v3"
)

const (
	EnvCradleHome        = "CRADLE_HOME"
	CradleConfigFileName = "cradle.yaml"

	CradleConfigFileHeader = `# Code generated by cradle. DO NOT EDIT.`
)

// cradleConfig is used for YAML marshaling
type cradleConfig struct {
	Projects []types.CradleProject `yaml:"projects"`
}

type Config struct {
	CradleHomeDirPath    string
	CradleConfigFilePath string
	CradleCommandOut     bool
	projects             []types.CradleProject
}

var instance Config

func Get() Config {
	return instance
}

// Init initializes the config singleton from CRADLE_HOME env (default ~/cradle), ensures directories/files exist, parses projects from YAML.
func Init() error {
	instance = Config{}

	instance.CradleCommandOut = slices.Contains(
		[]string{"1", "true", "TRUE", "True"},
		strings.TrimSpace(os.Getenv("CRADLE_CMDOUT")),
	)

	cradleHomePath, err := getCradleHomeDir()
	if err != nil {
		return err
	}

	err = ensureCradleHomeDir(cradleHomePath)
	if err != nil {
		return err
	}

	cradleConfigFilePath, err := ensureCradleConfigFile(cradleHomePath)
	if err != nil {
		return err
	}

	projects, err := parseCradleConfigFile(cradleConfigFilePath)
	if err != nil {
		return err
	}

	instance.CradleHomeDirPath = cradleHomePath
	instance.CradleConfigFilePath = cradleConfigFilePath
	instance.projects = projects

	return nil
}

func Projects() []types.CradleProject {
	projects := make([]types.CradleProject, len(instance.projects))
	copy(projects, instance.projects)
	return projects
}

// AddProject appends the project to the list and persists config to disk.
func AddProject(project types.CradleProject) error {
	instance.projects = append(instance.projects, project)
	return save()
}

// RemoveProjectByName removes a project matching the given name or path.
func RemoveProjectByName(name string) error {
	for i, project := range instance.projects {
		if project.MatchPathOrName(name) {
			instance.projects = append(instance.projects[:i], instance.projects[i+1:]...)
			return save()
		}
	}
	return fmt.Errorf("project not found")
}

// UpdateProjects replaces the projects list and persists to disk.
func UpdateProjects(projects []types.CradleProject) error {
	instance.projects = projects
	return save()
}

// ForEachProject iterates projects calling fn on each; stops early if fn returns false.
func ForEachProject(fn func(types.CradleProject) bool) {
	for _, project := range instance.projects {
		if !fn(project) {
			return
		}
	}
}

// FindProject returns first project matching query by path or unique name.
func FindProject(query string) (types.CradleProject, bool) {
	for _, project := range instance.projects {
		if project.MatchPathOrName(query) {
			return project, true
		}
	}
	return types.CradleProject{}, false
}

func TemporaryProjects() []types.CradleProject {
	var temp []types.CradleProject
	for _, project := range instance.projects {
		if project.Temporary {
			temp = append(temp, project)
		}
	}
	return temp
}

func PermanentProjects() []types.CradleProject {
	var permanent []types.CradleProject
	for _, project := range instance.projects {
		if !project.Temporary {
			permanent = append(permanent, project)
		}
	}
	return permanent
}

// save writes the sorted configuration to the YAML config file.
func save() error {
	slices.SortFunc(instance.projects, func(a, b types.CradleProject) int {
		return strings.Compare(a.Path, b.Path)
	})

	fileBytes, err := yaml.Marshal(cradleConfig{Projects: instance.projects})
	if err != nil {
		return err
	}

	fileBytes = append([]byte(CradleConfigFileHeader+"\n\n"), fileBytes...)

	return os.WriteFile(instance.CradleConfigFilePath, fileBytes, 0o666)
}

// getCradleHomeDir resolves the cradle home directory from the environment or returns the default.
func getCradleHomeDir() (string, error) {
	cradleHomePath := strings.TrimSpace(os.Getenv(EnvCradleHome))
	if cradleHomePath == "" {
		userHomeDir, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}

		cradleHomePath = path.Join(userHomeDir, "cradle")
	}

	return cradleHomePath, nil
}

// ensureCradleHomeDir creates the cradle home directory if it does not exist.
func ensureCradleHomeDir(dirPath string) error {
	dirStat, err := os.Stat(dirPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return os.MkdirAll(dirPath, os.ModePerm)
		}
		return err
	}

	if dirStat.IsDir() {
		return nil
	}

	return fmt.Errorf("%s is a file, either delete the file or change cradle home path by setting `CRADLE_HOME` env to something else", dirPath)
}

// ensureCradleConfigFile creates the config file if it does not exist and returns its path.
func ensureCradleConfigFile(dirPath string) (string, error) {
	configFilePath := path.Join(dirPath, CradleConfigFileName)

	configFileStat, err := os.Stat(configFilePath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			configFile, err := os.Create(configFilePath)
			if err != nil {
				return "", err
			}

			_, err = configFile.WriteString(CradleConfigFileHeader)
			if err != nil {
				return "", err
			}

			return configFilePath, nil
		}

		return "", err
	}

	if configFileStat.IsDir() {
		return "", fmt.Errorf("")
	}

	return configFilePath, nil
}

// parseCradleConfigFile reads and parses the config file, populating project unique names.
func parseCradleConfigFile(configFilePath string) ([]types.CradleProject, error) {
	var cradleConfig cradleConfig

	configFile, err := os.ReadFile(configFilePath)
	if err != nil {
		return nil, err
	}

	err = yaml.Unmarshal(configFile, &cradleConfig)
	if err != nil {
		return nil, err
	}

	slices.SortFunc(cradleConfig.Projects, func(a, b types.CradleProject) int {
		return strings.Compare(a.Path, b.Path)
	})

	nameLookup := make(map[string]struct{})
	for i, project := range cradleConfig.Projects {
		parts := strings.Split(project.Path, string(os.PathSeparator))
		for j := len(parts) - 1; j >= 0; j-- {
			candidateName := strings.Join(parts[j:], "/")
			if candidateName == "" {
				continue
			}

			if _, exists := nameLookup[candidateName]; !exists {
				cradleConfig.Projects[i].UniqueNameFromPath = candidateName
				nameLookup[candidateName] = struct{}{}
				break
			}
		}
	}

	return cradleConfig.Projects, nil
}
